### ISSUE TITLE
Import error when loading

### ISSUE THREAD

**Issue by aurel-g** [YinBailiang/MergeBlockWeighted_fo_ComfyUI#8]
```
Launching ComfyUI from: /mnt/comfyui/app

Total VRAM 16073 MB, total RAM 32000 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /mnt/comfyui/app/web
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/custom_nodes/MergeBlockWeighted_fo_ComfyUI/__init__.py", line 1, in <module>
    from .script import MergeBlockWeightedNodes as MBWNodes
  File "/mnt/comfyui/app/custom_nodes/MergeBlockWeighted_fo_ComfyUI/script/MergeBlockWeightedNodes.py", line 17, in <module>
    from comfy.sd import ModelPatcher
ImportError: cannot import name 'ModelPatcher' from 'comfy.sd' (/mnt/comfyui/app/comfy/sd.py)
```

**Comment by aurel-g** [comment]
Merged, thanks
